MovieRama.Web/Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieRama.Web.Controllers
{
    /// <summary>
    /// MVC controller for language operations
    /// </summary>
    public class LanguagesController : BaseController
    {
        /// <summary>
        /// Renders a drop down menu with the available languages of the application
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult Menu()
        {
            var languages = GetCachedLanguages();
            ViewBag.CurrentLanguage = languages.FirstOrDefault(f => f.Culture == CurrentCulture);

            return PartialView(languages);
        }
    }
}

MovieRama.Web/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieRama.EF;
using MovieRama.Core.Models;
using MovieRama.Resources.Messages;
using MovieRama.Web.Code.Enums;
using MovieRama.Web.Code.Attributes;

namespace MovieRama.Web.Controllers
{
    /// <summary>
    /// MVC controller for movie operations
    /// </summary>
    public class MoviesController : BaseController
    {
        /// <summary>
        /// The page with the list of movies
        /// </summary>
        /// <param name="searchModel">The parameters used for searching and sorting movies</param>
        /// <returns></returns>
        public ActionResult Index(MoviesSearchModel searchModel)
        {
            if (searchModel == null)
            {
                searchModel = new MoviesSearchModel();
            }
            searchModel.SanitizeProperties();
            searchModel.PageSize = DEFAULT_PAGE_SIZE;

            var model = this.Repo.GetMovies(CurrentCulture, searchModel, (CurrentUser != null) ? (int?)CurrentUser.Id : null);
            return View(model);
        }

        /// <summary>
        /// The page with the list of movies that are created by a specific user
        /// </summary>
        /// <param name="id">The id of the user</param>
        /// <param name="searchModel">The parameters used for searching and sorting movies</param>
        /// <returns></returns>
        public ActionResult ByUser(int id, MoviesSearchModel searchModel)
        {
            if (searchModel == null)
            {
                searchModel = new MoviesSearchModel();
            }
            searchModel.PageSize = DEFAULT_PAGE_SIZE;
            searchModel.UserId = id;
            searchModel.SanitizeProperties();

            var model = this.Repo.GetMovies(CurrentCulture, searchModel, (CurrentUser != null) ? (int?)CurrentUser.Id : null);
            return View("Index", model);
        }

        /// <summary>
        /// The movie creation page
        /// </summary>
        /// <returns></returns>
        [MRAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// The movie creation page (POST operation)
        /// </summary>
        /// <param name="model">The model for the new movie</param>
        /// <returns></returns>
        [MRAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MovieModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var errors = this.Repo.CreateMovie(model, User.Identity.Name);
            if (errors.Any())
            {
                this.AddModelErrors(errors);
                return View(model);
            }

            this.ShowNotification(MessagesResource.MovieCreatedSuccessMessage, ToastrNotificationType.Success);

            return RedirectToAction("Edit", new { id = model.Id });
        }

        /// <summary>
        /// The movie update page
        /// </summary>
        /// <param name="id">The id of the movie</param>
        /// <param name="languageId">The id of the language. It is used to update localized values of the movie</param>
        /// <returns></returns>
        [MRAuthorize]
        public ActionResult Edit(int id, int? languageId)
        {
            ViewBag.LanguageId = languageId;

            var movie = this.Repo.GetMovie(id, languageId);
            if (movie == null)
            {
                this.ShowNotification(MessagesResource.MovieNotFoundErrorMessage, ToastrNotificationType.Error);
                return RedirectToAction("Index");
            }
            if (movie.CreatorId != this.CurrentUser.Id)
            {
                this.ShowNotification(MessagesResource.NotAuthorizedToEditMovieErrorMessage, ToastrNotificationType.Error);
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        /// <summary>
        /// The movie update page (POST operation)
        /// </summary>
        /// <param name="model">The model for the movie</param>
        /// <param name="languageId">The id of the language. It is used to update localized values of the movie</param>
        /// <returns></returns>
        [MRAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MovieModel model, int? languageId)
        {
            ViewBag.LanguageId = languageId;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var movie = this.Repo.GetMovie(model.Id, languageId);
            if (movie == null)
            {
                this.ShowNotification(MessagesResource.MovieNotFoundErrorMessage, ToastrNotificationType.Error);
                return RedirectToAction("Index");
            }
            if (movie.CreatorId != this.CurrentUser.Id)
            {
                this.ShowNotification(MessagesResource.NotAuthorizedToEditMovieErrorMessage, ToastrNotificationType.Error);
                return RedirectToAction("Index");
            }

            var errors = this.Repo.UpdateMovie(model, languageId);
            if (errors.Any())
            {
                this.AddModelErrors(errors);
                return View(model);
            }

            this.ShowNotification(MessagesResource.MovieUpdatedSuccessMessage, ToastrNotificationType.Success);

            return View(model);
        }

        /// <summary>
        /// The movie deletion process
        /// </summary>
        /// <param name="id">The id of the movie to delete</param>
        /// <returns></returns>
        [MRAuthorize]
        public ActionResult Delete(int id)
        {
            var movie = this.Repo.GetMovie(id, null);
            if (movie == null)
            {
                this.ShowNotification(MessagesResource.MovieNotFoundErrorMessage, ToastrNotificationType.Error);
                return RedirectToAction("Index");
            }
            if (movie.CreatorId != this.CurrentUser.Id)
            {
                this.ShowNotification(MessagesResource.NotAuthorizedToDeleteMovieErrorMessage, ToastrNotificationType.Error);
                return RedirectToAction("Index");
            }

            var errors = this.Repo.DeleteMovie(id);
            if (errors.Any())
            {
                foreach (string error in errors)
                {
                    this.ShowNotification(error, ToastrNotificationType.Error);
                }
            }

            this.ShowNotification(MessagesResource.MovieDeletedSuccessMessage, ToastrNotificationType.Success);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Renders a drop down menu with the available languages of the application
        /// </summary>
        /// <param name="id">The id of the movie</param>
        /// <param name="languageId">The id of the language. It is used to update localized values of the movie</param>
        /// <returns></returns>
        [MRAuthorize]
        [ChildActionOnly]
        public ActionResult Languages(int id, int? languageId)
        {
            var languages = GetCachedLanguages();
            ViewBag.MovieId = id;

            var currentLanguage = languages.FirstOrDefault(f => f.Id == languageId);
            if (currentLanguage == null)
            {
                currentLanguage = languages.FirstOrDefault(f => f.IsDefault);
            }
            if (currentLanguage == null)
            {
                currentLanguage = languages.FirstOrDefault();
            }

            ViewBag.CurrentLanguage = currentLanguage;

            return PartialView(languages);
        }
    }
}

MovieRama.Web/Views/Shared/Menu.cshtml
@{
    string controller = ViewContext.RequestContext.RouteData.Values["controller"].ToString().ToLower();
    string action = ViewContext.RequestContext.RouteData.Values["action"].ToString().ToLower();
}

<ul class="nav navbar-nav">
    @if (User.Identity.IsAuthenticated)
    {
        <li class="@((controller == "movies" && action == "index") ? "active" : string.Empty)">
            <a href="@Url.Action("Index", "Movies", new { id = string.Empty })">
                @MessagesResource.AllMoviesMenuLink
            </a>
        </li>
        <li class="@((controller == "movies" && action == "create") ? "active" : string.Empty)">
            <a href="@Url.Action("Create", "Movies")">
                @MessagesResource.NewMovieMenuLink
            </a>
        </li>
        <li class="dropdown @((controller == "account") ? "active" : string.Empty)">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                @MessagesResource.MyAccountMenuLink
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li class="@((controller == "account" && action == "index") ? "active" : string.Empty)">
                    <a href="@Url.Action("Index", "Account")">
                        @MessagesResource.MyProfileMenuLink
                    </a>
                </li>
                <li class="@((controller == "account" && action == "changepassword") ? "active" : string.Empty)">
                    <a href="@Url.Action("ChangePassword", "Account")">
                        @MessagesResource.ChangePasswordMenuLink
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("SignOut", "Auth")">
                        @MessagesResource.SignOutMenuLink
                    </a>
                </li>
            </ul>
        </li>
    }
    else
    {
        <li class="@((controller == "movies" && action == "index") ? "active" : string.Empty)">
            <a href="@Url.Action("Index", "Movies")">
                @MessagesResource.AllMoviesMenuLink
            </a>
        </li>
        <li class="@((controller == "auth" && action == "login") ? "active" : string.Empty)">
            <a href="@Url.Action("Login", "Auth")">
                @MessagesResource.LoginMenuLink
            </a>
        </li>
        <li class="@((controller == "auth" && action == "register") ? "active" : string.Empty)">
            <a href="@Url.Action("Register", "Auth")">
                @MessagesResource.RegisterMenuLink
            </a>
        </li>
    }
</ul>

MovieRama.Web/Views/Shared/Notifications.cshtml
@if (TempData.ContainsKey("ToastrNotifications"))
{
    List<MovieRama.Web.Code.Models.ToastrNotificationModel> notifications = (List<MovieRama.Web.Code.Models.ToastrNotificationModel>)TempData["ToastrNotifications"];
    if (notifications.Any())
    {
        <script>
            @foreach(var notification in notifications)
            {
                switch(notification.Type)
                {
                    case MovieRama.Web.Code.Enums.ToastrNotificationType.Error:
                        <text>toastr.error('@notification.Message')</text>
                        break;
                    case MovieRama.Web.Code.Enums.ToastrNotificationType.Success:
                        <text>toastr.success('@notification.Message')</text>
                        break;
                    default:
                        <text>toastr.info('@notification.Message')</text>
                        break;
                }
            }
        </script>
    }
}

MovieRama.Web/Views/Shared/Pager.cshtml
@model MovieRama.Core.Models.Base.PagedListBase

@{
    var newQueryString = HttpUtility.ParseQueryString(Request.Url.Query);
    int limit = 5;
}

<ul class="pagination">
    @{ newQueryString["page"] = "1"; }
    <li class="@((Model.Page == 1) ? "disabled" : string.Empty)">
        <a href="?@newQueryString">&laquo;</a>
    </li>
    @if (Model.Page > limit)
    {
        newQueryString["page"] = (Model.Page - limit).ToString();
        <li>
            <a href="?@newQueryString"><</a>
        </li>
    }
    @for (int i = Model.Page - limit + 1; i < Model.Page + limit; i++)
    {
        if (i < 1 || i > Model.TotalPages)
        {
            continue;
        }

        newQueryString["page"] = i.ToString();
        <li class="@((Model.Page == i) ? "active" : string.Empty)">
            <a href="?@newQueryString">@i</a>
        </li>
    }
    @if (Model.Page < Model.TotalPages - limit)
    {
        newQueryString["page"] = (Model.Page + limit).ToString();
        <li>
            <a href="?@newQueryString">></a>
        </li>
    }
    @{ newQueryString["page"] = Model.TotalPages.ToString(); }
    <li class="@((Model.Page == Model.TotalPages) ? "disabled" : string.Empty)">
        <a href="?@newQueryString">&raquo;</a>
    </li>
</ul>

MovieRama.Web/Views/Shared/ValidationSummary.cshtml
@model ModelStateDictionary

@if (!Model.IsValid)
{
    <div class="alert alert-danger alert-dismissible fade in">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <ul>
            @foreach (var modelState in Model)
                {
                foreach (var error in modelState.Value.Errors)
                    {
                    if (!string.IsNullOrEmpty(error.ErrorMessage))
                        {
                        <li>@error.ErrorMessage</li>
                    }
                }
            }
        </ul>
    </div>
}

MovieRama.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title | Movie Rama</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/Content/assets/site.min.css" rel="stylesheet" />
    @RenderSection("Head", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Movie Rama", "Index", "Movies", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("Menu")
                @Html.Action("Menu", "Languages")
            </div>
        </div>
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <div class="container-fluid text-right">
            @MessagesResource.WelcomeBack:
            <a href="@Url.Action("ByUser", "Movies", new { id = ViewBag.User.Id })">@ViewBag.User.FirstName @ViewBag.User.LastName</a>
        </div>
        <br />
    }

    <div class="container body-content">
        @RenderBody()
    </div>

    <hr />
    <footer class="text-center">
        <p>&copy; @DateTime.Now.Year - Nikos Printezis</p>
    </footer>

    <script src="~/Content/assets/site.min.js"></script>
    <script>
        MovieRamaApp.culture = '@System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName';
    </script>
    @Html.Partial("Notifications")
    @RenderSection("Scripts", false)
    <script src="/Content/assets/js/localization/localization.@(System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName).js"></script>
</body>
</html>